version: '3.8'

services:
  user_service:
    build:
      context: ./user service
    container_name: user_service
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/neptune
      - DATABASE_USERNAME=ashish
      - DATABASE_PASSWORD=ashish123
      - KAFKA_SERVER=kafka:9092
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: neptune
      POSTGRES_USER: ashish
      POSTGRES_PASSWORD: ashish123
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2191:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9992:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


volumes:
  pgdata:
    driver: local
