spring.application.name=loan_service
server.port=8087
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/loan}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:ashish}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=user
spring.security.user.password=password
# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.roles=ADMIN
# EUREKA CLIENT CONFIG
eureka.instance.hostname=${HOSTNAME:localhost}
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.lease-renewal-interval-in-seconds=${EUREKA_TIME_INTERVAL:300}
eureka.instance.lease-expiration-duration-in-seconds=${EUREKA_EXPIRATION_INTERVAL:900}
eureka.client.registry-fetch-interval-seconds=${EUREKA_FETCH_INTERVAL:600}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# SPRING BOOT ADMIN CLIENT CONFIG
# Use service name in Admin dashboard
spring.boot.admin.client.instance.name=${spring.application.name}
spring.boot.admin.client.instance.service-base-url=${SERVICE_BASE_URL:http://localhost:${server.port}}
spring.boot.admin.client.url=${ADMIN_SERVER_URL:http://localhost:8761/}
spring.boot.admin.client.instance.metadata.show-sensitive=true
management.endpoint.health.probes.enabled=true
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always
spring.boot.admin.client.instance.metadata.user.name=${USER:user}
spring.boot.admin.client.instance.metadata.user.password=${PASSWORD:password}
# Logging configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
