spring.application.name=otp_service
server.port=8084
# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL:ashish23481@gmail.com}
spring.mail.password=${MAIL_PASSWORD:frxo dsvv gccp nfzu}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000`
# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/otp
spring.datasource.username=postgres
spring.datasource.password=ashish
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
# Kafka configuration
# Kafka bootstrap servers
spring.kafka.bootstrap-servers=${KAFKA_SERVER:http://localhost:9092}
# Security
spring.kafka.properties.security.protocol=${SASL_SSL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${SCRAM_SHA_512:PLAINTEXT}
spring.kafka.properties.sasl.jaas.config=${REDPANDA_CONFIG:PLAINTEXT};
# Consumer config
spring.kafka.consumer.group-id=${KAFKA_GROUP:user}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.max-poll-records=50
spring.kafka.consumer.properties.max.poll.interval.ms=300000
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.batch-size=32768
spring.kafka.producer.buffer-memory=67108864
spring.kafka.producer.compression-type=snappy
# Logging
logging.level.org.springframework.mail=DEBUG
# custom properties
sms.device-id=${DEVICE_ID:68874e962a7cd2adad19f770}
sms.api-key=${API_KRY:f4cb683f-1071-4285-a6eb-a5e3ebed910a}
sms.whatsapp-link=${WHATSAPP_LINK:http://localhost:3000/send-otp}
