spring.application.name=Neptune Bank
spring.security.user.name=user
spring.security.user.password=password
spring.datasource.url=jdbc:postgresql://localhost:5432/admin
spring.datasource.username=postgres
spring.datasource.password=ashish
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/admin
spring.r2dbc.username=postgres
spring.r2dbc.password=ashish
spring.sql.init.platform=postgres
# Server configuration
server.port=8088
