spring.application.name=Neptune Bank
spring.security.user.name=user
spring.security.user.password=password
# database configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/admin
spring.r2dbc.username=postgres
spring.r2dbc.password=ashish
spring.sql.init.platform=postgres
spring.sql.init.mode=always
# Server configuration
server.port=8080
# Gateway configuration
# auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH-SERVICE:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
# user-service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=${USER-SERVICE:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**
# account-service
spring.cloud.gateway.routes[2].id=account-service
spring.cloud.gateway.routes[2].uri=${USER-SERVICE:http://localhost:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/accounts/**
# messaging-service
spring.cloud.gateway.routes[3].id=messaging-service
spring.cloud.gateway.routes[3].uri=${MESSAGING-SERVICE:http://localhost:8084}
spring.cloud.gateway.routes[3].predicates[0]=Path=/messages/otp/**
# Custom properties
auth-service.url=${WEBCLIENT_URL:http://localhost:8081}
# cors configuration
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=${ORIGIN:http://192.168.197.207:5173,http://localhost:5173}
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
# security configuration
spring.main.allow-bean-definition-overriding=true
# logging configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
