spring.application.name=main_server
server.port=${PORT:8761}
spring.profiles.active=PROD
# eureka server configuration
eureka.instance.hostname=localhost
eureka.dashboard.path=/eureka
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${DEFAULT_ZONE:http://localhost:8761/admin/eureka/}
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=60000
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.response-cache-update-interval-ms=3000
# Admin server (self-register)
# Mount Spring Boot Admin under
server.servlet.context-path=/
# Actuator / Monitoring
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# Security
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
