spring.application.name=employee service
# Default profile
spring.profiles.active=${PROFILE:dev}
# Server configuration
server.port=${PORT:8086}
server.address=${HOST:localhost}
server.error.include-message=never
server.error.include-binding-errors=never
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
# flyway configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration
# Database configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/Employee}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:ashish}
spring.jpa.hibernate.ddl-auto=${DATABASE_DDL_AUTO:validate}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=NeptuneHikariCP
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never
# Kafka configuration
# Kafka bootstrap servers
spring.kafka.bootstrap-servers=${KAFKA_SERVER:http://localhost:9092}
# Security
spring.kafka.properties.security.protocol=${SASL_SSL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${SCRAM_SHA_512:PLAINTEXT}
spring.kafka.properties.sasl.jaas.config=${REDPANDA_CONFIG:PLAINTEXT};
# Consumer config
spring.kafka.consumer.group-id=${KAFKA_GROUP:user}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.max-poll-records=50
spring.kafka.consumer.properties.max.poll.interval.ms=300000
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.batch-size=32768
spring.kafka.producer.buffer-memory=67108864
spring.kafka.producer.compression-type=snappy
# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.roles=ADMIN
# EUREKA CLIENT CONFIG
eureka.instance.hostname=${HOSTNAME:localhost}
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.lease-renewal-interval-in-seconds=${EUREKA_TIME_INTERVAL:300}
eureka.instance.lease-expiration-duration-in-seconds=${EUREKA_EXPIRATION_INTERVAL:900}
eureka.client.registry-fetch-interval-seconds=${EUREKA_FETCH_INTERVAL:600}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# SPRING BOOT ADMIN CLIENT CONFIG
# Use service name in Admin dashboard
spring.boot.admin.client.instance.name=${spring.application.name}
spring.boot.admin.client.instance.service-base-url=${SERVICE_BASE_URL:http://localhost:${server.port}}
spring.boot.admin.client.url=${ADMIN_SERVER_URL:http://localhost:8761/}
spring.boot.admin.client.instance.metadata.show-sensitive=true
management.endpoint.health.probes.enabled=true
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always
spring.boot.admin.client.instance.metadata.user.name=${USER:user}
spring.boot.admin.client.instance.metadata.user.password=${PASSWORD:password}
# custom properties
app.secret-key=${SECRET_KEY:ashish}
