spring.application.name=messaging-service
server.port=8084
# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL:ashish23481@gmail.com}
spring.mail.password=${MAIL_PASSWORD:password lega}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000`
# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/otp
spring.datasource.username=postgres
spring.datasource.password=ashish
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
# Kafka configuration
# Kafka bootstrap servers
spring.kafka.bootstrap-servers=${KAFKA_SERVER:http://localhost:9092}
# Security
spring.kafka.properties.security.protocol=${SASL_SSL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${SCRAM_SHA_512:PLAINTEXT}
spring.kafka.properties.sasl.jaas.config=${REDPANDA_CONFIG:PLAINTEXT};
# Consumer config
spring.kafka.consumer.group-id=${KAFKA_GROUP:user}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.max-poll-records=50
spring.kafka.consumer.properties.max.poll.interval.ms=300000
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.batch-size=32768
spring.kafka.producer.buffer-memory=67108864
spring.kafka.producer.compression-type=snappy
# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.roles=ADMIN
# EUREKA CLIENT CONFIG
eureka.instance.hostname=${HOSTNAME:localhost}
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.lease-renewal-interval-in-seconds=${EUREKA_TIME_INTERVAL:300}
eureka.instance.lease-expiration-duration-in-seconds=${EUREKA_EXPIRATION_INTERVAL:900}
eureka.client.registry-fetch-interval-seconds=${EUREKA_FETCH_INTERVAL:600}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# SPRING BOOT ADMIN CLIENT CONFIG
# Use service name in Admin dashboard
spring.boot.admin.client.instance.name=${spring.application.name}
spring.boot.admin.client.instance.service-base-url=${SERVICE_BASE_URL:http://localhost:${server.port}}
spring.boot.admin.client.url=${ADMIN_SERVER_URL:http://localhost:8761/}
spring.boot.admin.client.instance.metadata.show-sensitive=true
management.endpoint.health.probes.enabled=true
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always
# custom properties
sms.device-id=${DEVICE_ID:hehehehehehehehehe}
sms.api-key=${API_KRY:hahahahahahahahaha}
sms.whatsapp-link=${WHATSAPP_LINK:http://localhost:3000/send-otp}
app.secret-key=${SECRET_KEY:ashish}
# Logging configuration
logging.level.root=INFO
logging.level.org.springframework=${LOGGING:DEBUG}
logging.level.org.springframework.security=${LOGGING:DEBUG}
logging.level.org.springframework.kafka.listener.KafkaMessageListenerContainer=${LOGGING:INFO}
