-- Table: branch
CREATE TABLE branch
(
    branch_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name    VARCHAR(255) NOT NULL,
    branch_code    VARCHAR(255) NOT NULL UNIQUE,
    branch_address TEXT         NOT NULL,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL
);

-- Useful index for searching by name/code
CREATE INDEX idx_branch_name ON branch (branch_name);
CREATE INDEX idx_branch_code ON branch (branch_code);

-- Table: limit
CREATE TABLE limit
(
    limit_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_limit                  BIGINT NOT NULL DEFAULT 100000,
    remaining_daily_limit        BIGINT NOT NULL DEFAULT 100000,
    monthly_limit                BIGINT NOT NULL DEFAULT 1000000,
    remaining_monthly_limit      BIGINT NOT NULL DEFAULT 1000000,
    rtgs_daily_limit             BIGINT NOT NULL DEFAULT 200000,
    remaining_rtgs_daily_limit   BIGINT NOT NULL DEFAULT 200000,
    rtgs_monthly_limit           BIGINT NOT NULL DEFAULT 2000000,
    remaining_rtgs_monthly_limit BIGINT NOT NULL DEFAULT 2000000,
    imps_daily_limit             BIGINT NOT NULL DEFAULT 50000,
    remaining_imps_daily_limit   BIGINT NOT NULL DEFAULT 50000,
    imps_monthly_limit           BIGINT NOT NULL DEFAULT 500000,
    remaining_imps_monthly_limit BIGINT NOT NULL DEFAULT 500000,
    neft_daily_limit             BIGINT NOT NULL DEFAULT 150000,
    remaining_neft_daily_limit   BIGINT NOT NULL DEFAULT 150000,
    neft_monthly_limit           BIGINT NOT NULL DEFAULT 1500000,
    remaining_neft_monthly_limit BIGINT NOT NULL DEFAULT 1500000,
    upi_daily_limit              BIGINT NOT NULL DEFAULT 200000,
    remaining_upi_daily_limit    BIGINT NOT NULL DEFAULT 200000,
    created_at                   TIMESTAMP,
    updated_at                   TIMESTAMP
);

-- Table: account
CREATE TABLE account
(
    account_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT         NOT NULL,
    branch_id             BIGINT         NOT NULL,
    limit_id              BIGINT         NOT NULL UNIQUE,
    account_type          VARCHAR(255)   NOT NULL,
    account_number        VARCHAR(255)   NOT NULL UNIQUE,
    balance               NUMERIC(19, 2) NOT NULL DEFAULT 50000.00,
    status                VARCHAR(255)   NOT NULL DEFAULT 'PENDING_VERIFICATION',
    mode_of_operation     VARCHAR(255)   NOT NULL,
    account_interest_rate NUMERIC(7, 4)  NOT NULL,
    rejection_reason      VARCHAR(255)   NOT NULL DEFAULT '',
    created_at            TIMESTAMP      NOT NULL,
    updated_at            TIMESTAMP      NOT NULL,

    CONSTRAINT fk_account_branch FOREIGN KEY (branch_id)
        REFERENCES branch (branch_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_account_limit FOREIGN KEY (limit_id)
        REFERENCES limit (limit_id)
        ON DELETE CASCADE
);

-- Helpful indexes for querying by user and branch
CREATE INDEX idx_account_user_id ON account (user_id);
CREATE INDEX idx_account_branch_id ON account (branch_id);

-- Table: upi
CREATE TABLE upi
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT       NOT NULL UNIQUE,
    upi_id     VARCHAR(255) NOT NULL UNIQUE,
    status     VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_upi_account FOREIGN KEY (account_id)
        REFERENCES account (account_id)
        ON DELETE CASCADE
);
