vaadin.launch-browser=true
spring.application.name=banking_service
server.port=8083
# session configuration
server.servlet.session.cookie.name=BANKING_SESSION_ID
# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=ashish
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# Kafka configuration
# Kafka bootstrap servers
spring.kafka.bootstrap-servers=${KAFKA_SERVER:http://localhost:9092}
# Security
spring.kafka.properties.security.protocol=${SASL_SSL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${SCRAM_SHA_512:PLAINTEXT}
spring.kafka.properties.sasl.jaas.config=${REDPANDA_CONFIG:PLAINTEXT};
# Consumer config
spring.kafka.consumer.group-id=${KAFKA_GROUP:user}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.max-poll-records=50
spring.kafka.consumer.properties.max.poll.interval.ms=300000
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.batch-size=32768
spring.kafka.producer.buffer-memory=67108864
spring.kafka.producer.compression-type=snappy
# Logging configuration
logging.level.org.springframework=INFO
logging.level.org.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# custom configuration
app.secret-key=${SECRET_KEY:ashish}
