spring.application.name=account-service
spring.datasource.url=jdbc:postgresql://localhost:5433/AccountDB
spring.datasource.username=neptune
spring.datasource.password=ankit
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
server.port=8083
logging.level.org.springframework.security=DEBUG
spring.security.user.name=admin
spring.security.user.password=admin
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate=DEBUG
spring.rabbitmq.port=5672
spring.rabbitmq.host=localhost
spring.rabbitmq.username=neptune
spring.rabbitmq.password=ankit
rabbitmq.user.validation.request.queue=${queue:queue}
rabbitmq.exchange.name=${exchange:exchange}
rabbitmq.user.validation.routing=${routingKey:routingKey}
security.jwt.public-key-location=classpath:public.pem
eureka.client.serviceUrl.defaultZone=http://neptune-hub:8085/eureka/
spring.boot.admin.client.url=http://neptune-hub:8085
management.endpoints.web.exposure.include=health,info,metrics


