spring.application.name=transaction service
# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/transactions
spring.datasource.username=postgres
spring.datasource.password=ashish
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# JPA configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Logging configuration
logging.level.org.springframework=INFO
logging.level.sql=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# Server configuration
server.port=8086
