spring.application.name=auth_service
server.port=${PORT:8081}
#Logging configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.roles=ADMIN
# EUREKA CLIENT CONFIG
eureka.instance.hostname=${HOSTNAME:localhost}
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.lease-renewal-interval-in-seconds=${EUREKA_TIME_INTERVAL:300}
eureka.instance.lease-expiration-duration-in-seconds=${EUREKA_EXPIRATION_INTERVAL:900}
eureka.client.registry-fetch-interval-seconds=${EUREKA_FETCH_INTERVAL:600}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# SPRING BOOT ADMIN CLIENT CONFIG
# Use service name in Admin dashboard
spring.boot.admin.client.instance.name=${spring.application.name}
spring.boot.admin.client.instance.service-base-url=${SERVICE_BASE_URL:http://localhost:${server.port}}
spring.boot.admin.client.url=${ADMIN_SERVER_URL:http://localhost:8761/}
spring.boot.admin.client.instance.metadata.show-sensitive=true
management.endpoint.health.probes.enabled=true
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always
spring.boot.admin.client.instance.metadata.user.name=${USER:user}
spring.boot.admin.client.instance.metadata.user.password=${PASSWORD:password}
# custom properties
app.secret-key=${SECRET_KEY:ashish}
app.login-url=${LOGIN_URL:http://localhost:8086/auth/login}
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{36}) - %msg%n}
